#!/usr/bin/env bash
# Installs and configures HAProxy for round robin load balancing

apt-get update -y
apt-get install haproxy -y

mkdir -p /run/haproxy
echo "ENABLED=1" > /etc/default/haproxy

cat > /etc/haproxy/haproxy.cfg << 'EOF'
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	daemon
	h1-case-adjust x-served-by X-Served-By

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
	option	h1-case-adjust-bogus-client
	timeout connect 5000
	timeout client  50000
	timeout server  50000

frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server 7154-web-01 184.72.105.193:80 check
	server 7154-web-02 52.23.236.50:80 check
EOF

service haproxy restart
