#!/usr/bin/env bash
# Transfers a file to a server using scp
#store arguments in named variables
FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4
# Check asruments
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

#Transfer the file
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$IP":~/
