#!/usr/bin/env bash
# Installs and configures nginx to serve Holberton School page on port 80

apt-get update -y
apt-get install nginx -y

echo "Holberton School for the win!" > /var/www/html/index.html

service nginx start
service nginx reload
